[project]
name = "wminhyuk-eda"
version = "0.4.0"
description = "Default template for PDM package"
authors = [
    {name = "<wminhyuk>", email = "<seoseo1998@gmail.com>"},
]
dependencies = [
    "pandas>=2.2.3",
    "president-speech>=0.9.1",
    "typer>=0.15.1",
]
requires-python = "==3.10.*"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = false


[dependency-groups]
eda = [
    "jupyterlab>=4.3.4",
]
test = [
    "pytest>=8.3.4",
]

[project.scripts]
wminhyuk-eda = "wminhyuk_eda.cli:group_by_count"
wminhyuk-eda-olympic = "wminhyuk_eda_olympic.cli:group_by_count"
